#Import methods in Python

In [1]:
import math #this will import math module to python file

In [5]:
A = 4
print(math.sqrt(A)) #using sqrt method of math module

2.0


In [9]:
from math import sin #to import specific method from module

In [11]:
A = 1
print(sin(A))

0.8414709848078965


#Universal Functions in NumPy

In [12]:
#sqrt function
import numpy as np

In [17]:
np_sqrt = np.sqrt([4,9,16]) #use of Numpy sqrt function, will apply the sqrt on the whole array
print(np_sqrt)

[2. 3. 4.]


In [18]:
#use of trigonometric functions
np.cos(0)

1.0

In [20]:
from numpy import pi
np.sin(pi/2)

1.0

In [21]:
np.cos(pi)

-1.0

In [22]:
np.floor([1.5,1.6,2.7]) #returns the largest value of every integer value in the array

array([1., 1., 2.])

In [24]:
np.exp([0,1,5]) #performs exponentiation on each element

array([  1.        ,   2.71828183, 148.4131591 ])

#SHAPE MANIPULATION

In [5]:
#FLATTENS
import numpy as np
new_array = np.array([[10,15,54,78,32], [23,56,47,58,696]])
new_array.ravel() #ravel() function is used to flatten the dataset into a single row

array([ 10,  15,  54,  78,  32,  23,  56,  47,  58, 696])

In [12]:
#RESHAPE
new_array.reshape(5,2) #reshape(), it will reshape  the array

array([[ 10,  15],
       [ 54,  78],
       [ 32,  23],
       [ 56,  47],
       [ 58, 696]])

In [14]:
#RESIZE
new_array.resize(2,5) #resize the array again
new_array

array([[ 10,  15,  54,  78,  32],
       [ 23,  56,  47,  58, 696]])

In [15]:
#SPLIT, HSPLIT
np.split(new_array,2) #it will split the array into two arrays

[array([[10, 15, 54, 78, 32]]), array([[ 23,  56,  47,  58, 696]])]

In [19]:
#stack
array_1 = np.array([10, 15, 54, 78, 32])
array_2 = np.array([23, 56, 47, 58, 696])
np.hstack((array_1, array_2)) #it will stack the arrays together

array([ 10,  15,  54,  78,  32,  23,  56,  47,  58, 696])

In [20]:
import numpy as np

In [21]:
#create a simple numpy ndarray
first_numpy_array = np.array([1,2,3,4])
print(first_numpy_array)

[1 2 3 4]


In [23]:
#array with zeros
zeros_array = np.zeros((3,3))
print(zeros_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [24]:
#array with ones
ones_array = np.ones((3,3))
print(ones_array)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [32]:
#array with empty
empty_array = np.empty((2,3))
empty_array

array([[0., 0., 0.],
       [0., 0., 0.]])

In [35]:
#array with arrange method
arange_array = np.arange(12)
print(arange_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [36]:
#reshape the array
arange_array.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [37]:
#linespace for linearly (equal) spaced data elements
linspace_array = np.linspace(1,6,5) #contain 3 arguments (first number, last number, total NO of equidistant elements)
print(linspace_array)

[1.   2.25 3.5  4.75 6.  ]


In [38]:
#one dimensional array
oneD_array = np.arange(15)
print(oneD_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [39]:
#two dimensionl array
twoD_array = oneD_array.reshape(3,5)
print(twoD_array)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [40]:
#Three dimensional array
ThreeD_array = np.arange(27).reshape(3,3,3)
print(ThreeD_array)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [1]:
import numpy as np

In [2]:
#o dimensional array
np.array(25)

array(25)

In [3]:
#one Dimensional array
np.array([4,8,6,4])

array([4, 8, 6, 4])

In [6]:
#two dimensional array
TwoD_array = np.array([[1,5,2,5],[4,7,8,9]])
TwoD_array

array([[1, 5, 2, 5],
       [4, 7, 8, 9]])

In [8]:
TwoD_array.shape #shape of array, rows and coloumns

(2, 4)

In [9]:
TwoD_array.ndim #represent dimensions of array

2